project:
  type: website
  output-dir: docs

website:
  title: "Mathe mit Lennart"
  navbar:
    pinned: true
  site-url: https://loelschlaeger.de/mathe-mit-lennart
  page-footer:
    center: 
      - text: "© 2023 Lennart Oelschläger"
        href: https://loelschlaeger.de
  search: 
    limit: 3
  repo-url: https://github.com/loelschlaeger/mathe-mit-lennart
  repo-actions: [edit, issue]

format:
  html:
    theme: simplex
    lang: "de"
    css: styles.css
    
comments:
  utterances:
    repo: loelschlaeger/mathe-mit-lennart



