---
title: "Adjunktion"
---

Zwei [Aussagen](aussagen.qmd) $A$ und $B$ kann man mit *oder* ($A \lor B$) [verknüpfen](verknuepfung.qmd). Das bedeutet, dass die Gesamtaussage wahr ist, wenn mindestens eine der beiden Aussagen wahr ist. Andernfalls ist sie falsch.

Hier ist eine [Wahrheitstafel](wahrheitstafel.qmd), die zeigt, wie das funktioniert:

| $A$   | $B$   | $A \lor B$ |
| --- | --- | ----- |
| wahr   | wahr   | wahr     |
| wahr   | falsch   | wahr     |
| falsch   | wahr   | wahr     |
| falsch   | falsch   | falsch     |

Das bedeutet, dass die Aussage $A \lor B$ wahr ist, wenn entweder $A$ oder $B$ (oder beide) wahr sind. Es ist nur dann falsch, wenn beide Aussagen $A$ und $B$ falsch sind.

Beispiel: Wenn $A$ die Aussage "Die Sonne scheint" ist und $B$ die Aussage "Es regnet" ist, dann ist $A \lor B$ die Aussage "Die Sonne scheint oder es regnet." Diese Gesamtaussage ist wahr, wenn entweder die Sonne scheint oder es regnet, aber falsch, wenn weder die Sonne scheint noch es regnet.